### ISSUE TITLE
Feature-Request: use proxy-configuration from environment variables

### ISSUE THREAD

**Issue by donfranio** [lilydjwg/nvchecker#101]
As far as I can see you can only configure a proxy for nvchecker via the config-file.

It would be cool, if nvchecker would consider the environment variable if nothing is provided in the configuration-file.

**Comment by juliantaylor** [comment]
you probably have to add `trust_env=True` to the `aiohttp.ClientSession` usage for it to work.

**Comment by lilydjwg** [comment]
It's nice to have this feature but I don't have the time to implement it. Patches are welcome. Before this is implemented, you can use proxychains or similar to use proxies.

BTW tornado + pycurl is the recommended HTTP client.

**Comment by lilydjwg** [comment]
Environment variables for proxy support will be used if the HTTP backend supports, and the latest tornado + pycurl supports them well.
