### ISSUE TITLE
include_regex does not work with pagination

### ISSUE THREAD

**Issue by juliantaylor** [lilydjwg/nvchecker#103]
for repositories with so many tags that it needs multiple pages `include_regex` does not work while the deprecated `include_tags_pattern` does work

For example following repository returns no result with the new setting but does return results with the old setting:

```
[puppetserver]
github = puppetlabs/puppetserver
use_max_tag = true
max_page = 5
include_regex = ^[0-9.]+
```

with instead

    include_tags_pattern = ^[0-9.]+

it currently correctly returns `6.2.1`

it appears apply_list_options only gets the first page multiple times, not each page:
```
>/.local/lib/python3.6/site-packages/nvchecker-1.4.2-py3.6.egg/nvchecker/get_version.py(46)apply_list_options()
-> if pattern:
(Pdb) p len(versions), len(set(versions))
(150, 30)
```

**Comment by juliantaylor** [comment]
The problem is likely only in the github source here:
https://github.com/lilydjwg/nvchecker/blob/master/nvchecker/source/github.py#L106

when it finds data it just iterates the same page every time instead of switching to the next page
so it works only by accident with the source regex as it returns no data the first time and then switches to the next page where it finds data and stops.
So it is technically broken also in the previous version.

**Comment by lilydjwg** [comment]
Oops, there was a logic error.

I've changed the API in use so I can get more tags with less pages. Hope it works without issues. (I'll make a release tomorrow if everything works fine.)

**Comment by lilydjwg** [comment]
In versions < 1.4 there was no list options. In 1.3 it worked because the logic was correct, but was broken when list options and `max_page` was added.

**Comment by juliantaylor** [comment]
thanks, I tested current master with my configuration (47 sources of various types) and all is working fine.
