### ISSUE TITLE
Github release tag

### ISSUE THREAD

**Issue by tomposmiko** [lilydjwg/nvchecker#106]
hi,

Your tools is awesome, thanks for it.

Funny, but for `nvchecker` release check does not work (only commit can be checked):

Where it works properly this endpoint returns with valid information:
https://api.github.com/repos/go-gitea/gitea/releases/latest

For your repo it does not work:

https://api.github.com/repos/lilydjwg/nvchecker/releases/latest

However, both Github projects have releases on the project page. So I simply don't understand, why is that? Why is that endpoint is missing for nvchecker?

**Comment by tomposmiko** [comment]
I see it working with use_max_tag, but still it's not clear to me, why the release endpoint is missing?

**Comment by lilydjwg** [comment]
Because I didn't make my releases the GitHub way. Instead of opening the web page and filling in the form, I use the `git tag` command. I don't think it's necessary to make GitHub releases since I've already released them on PyPI.

**Comment by tomposmiko** [comment]
I see the point now.
Why does Github provide a different solution to this problem?
Thanks anyway.
