### ISSUE TITLE
Intended usage

### ISSUE THREAD

**Issue by chazanov** [lilydjwg/nvchecker#111]
I've just found this tool and thought "how great". But I don't really get how to use it.

Here is my config:

```
[__config__]
oldver = old_ver.txt
newver = new_ver.txt

[holoviews]
github = pyviz/holoviews
```

old_ver contains
`holoviews 20190721.234313`

and new_ver
`holoviews 20190717.131740`

But the newest version in reality is [1.12.3 from the 20th of May](https://github.com/pyviz/holoviews/releases).

Why is nvchecker finding daily snapshots here?

**Comment by lilydjwg** [comment]
You need to add `use_latest_release = true` if you want to check for new releases from GitHub.

nvchecker is intended for packagers and developers to get aware of updates of software. It was started as a tool for the archlinuxcn unofficial package repository and finds good usage to keep packages up-to-date. End users and other people may find it useful too but they may be confused because I don't really know what they may want from it.

**Comment by chazanov** [comment]
Should I put _use_latest_release_ into [__config__] or at every entry?

**Comment by lilydjwg** [comment]
Every entry (you need). This kind of config is per-entry.

**Comment by chazanov** [comment]
@lilydjwg My package of nvchecker got updated through your great archlinuxcn repo – and now 95 % of all github fetches fail with `error=HTTP 404: Not Found`, despite the repos [obviously exist](wireservice/agate-excel).

Here is a minimal example, which always fail:

```
[__config__]
oldver = old_ver.txt
newver = new_ver.txt

[wire_agate-excel]
github = wireservice/agate-excel
use_latest_release = true
```

**Comment by lilydjwg** [comment]
No, this repo doesn't not have any *GitHub releases*; it only has tags. You need to replace `use_latest_release` with `use_max_tag`.

I don't know why it worked for you before. This code has been there for about four years.

**Comment by chazanov** [comment]
Ok, I'm very sorry. Does it mean that most projects never create releases, but only _tags_?
http://github.com/wireservice/agate-excel/releases

**Comment by lilydjwg** [comment]
GitHub shows two kinds of releases: one created via GitHub webpage and one via git tags. And only the former shows up in the releases API.

The wireservice/agate-excel repo uses the latter. [ripgrep](https://github.com/BurntSushi/ripgrep/releases) and [zfs](https://github.com/zfsonlinux/zfs/releases) uses the former.
