### ISSUE TITLE
Tests fail when not connected to internet

### ISSUE THREAD

**Issue by jayvdb** [lilydjwg/nvchecker#113]
While bundling this for openSUSE, the tests are run inside an isolated VM, disconnected from the internet.

Some mechanism is needed to get the rest of the  tests to pass, and these ones to be skipped.

Options include
- a pytest mark on internet tests, or non-internet tests, so `pytest -k notnet` or `pytest -k 'not net` can be used
- split the tests into two subdirectories, one for infrastructure code and the other for resolvers needing network
- detect network is missing in a pytest fixture and dynamically skip those tests
- adding mocks for the tests

A quick win for `tests/test_regex.py` is to use the pytest plugin for httpbin, which provides a local instance of httpbin that works in an isolated VM.

Probably other approaches exist too.

Atm I am doing

```console
mkdir tests_ok
mv tests/test_cache.py \
   tests/test_cmd.py \
   tests/test_manual.py \
   tests/test_substitute.py \
   tests/conftest.py \
   tests_ok
pytest tests_ok/
```

Project at https://build.opensuse.org/package/show/home:jayvdb:py-new/python-nvchecker

**Comment by lilydjwg** [comment]
I've added a `needs_net` mark so you can run `pytest -m 'not needs_net'`. I also make use of pytest-httpbin, thanks for your recommendation!

**Comment by jayvdb** [comment]
Thanks. Looking forward to the next release.
