### ISSUE TITLE
pip3 install nvchecker error on Linux

### ISSUE THREAD

**Issue by chengcxy** [lilydjwg/nvchecker#124]
__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory: 'curl-config': 'curl-config'

**Comment by lilydjwg** [comment]
You failed to install pycurl because there is no binary release for your system and you don't have curl develop files installed. You need to install them using your package manager. The package name may be libcurl-devel (for rpm distributions) or libcurl4-openssl-dev (for Debian).

**Comment by chengcxy** [comment]
依云小姐姐，Linux 安装libcurl-devel 后 pip3 install nvchecker 安装成功  但找不到nvchecker命令行  "bash: nvchecker: 未找到命令"  mac上没问题 不知道您这边测试过没有~







在 2020-01-08 13:16:31，"依云" <notifications@github.com> 写道：

Closed #124.

**Comment by chengcxy** [comment]
找到问题 系统环境变量问题 囧。






依云小姐姐，Linux 安装libcurl-devel 后 pip3 install nvchecker 安装成功  但找不到nvchecker命令行  "bash: nvchecker: 未找到命令"  mac上没问题 不知道您这边测试过没有~







在 2020-01-08 13:16:31，"依云" <notifications@github.com> 写道：

Closed #124.
