### ISSUE TITLE
AUR rpc can fetch multiple packages at once

### ISSUE THREAD

**Issue by farseerfc** [lilydjwg/nvchecker#132]
Currently we fetch each package with a seperate RPC request in here:
https://github.com/lilydjwg/nvchecker/blob/fbdde9bf585b2a315ed402d273e5e96613453d30/nvchecker/source/aur.py#L19

With a lots of packages this may hit the RPC rate limits.
AUR RPC can fetch multiple packages as documented here: https://wiki.archlinux.org/index.php/Aurweb_RPC_interface#info
From the source code it seems this can handle 5000 packages per request (https://github.com/lfos/aurweb/blob/300641ddbdd6e22aff9a5052ed07d409d9912b68/conf/config.defaults#L23
and https://github.com/lfos/aurweb/blob/b64e195237edd69cd61e407c3cb10282b9c1ee33/web/lib/aurjson.class.php#L355)

Thus we may refactor nvchecker to fetch more package infos, possibly all of them put in a single request as currently we do not have more than 5000 packages in our repo.

**Comment by lilydjwg** [comment]
This has been implemented in 14b3863f11fe72f0cd753a6724c093d1661dfc00 and 0232d0fb4f9fa170f89bcb6765950e015c137052.
