### ISSUE TITLE
RFE: Support external/custom version sources (plugins)

### ISSUE THREAD

**Issue by jruzicka-nic** [lilydjwg/nvchecker#133]
After inspecting `nvchecker` source code I found no way to include custom version handlers without core code modification as they seem to be hardcoded into `handlers_precedence` list and loading is always done from `nvchecker.source` package.

Instead of forking/rewriting/reinventing the wheel, I'd prefer to extend `nvchecker` with a simple **plugin system**:

* put custom version sources into a predefined user directory (`~/.nvchecker/sources` ?) OR custom directory specified with new CLI argument (`--extra-sources my_nv_sources_dir`)
* load all valid extra source handlers and use them the very same way as those included in `nvchecker.source`

That way, users can:

* use `nvchecker` and its nice version handlers alongside custom handlers to get versions from all possible sources including those that aren't generic enough to have an upstream handler
* use/test custom handlers without forking `nvchecker` and optionally submit them easily for upstream inclusion

**I'm willing and able to implement this** if upstream is interested - please do let me know and I'll start hacking. Otherwise I'll be forced to create a competing project :)

**Comment by jruzicka-nic** [comment]
@lilydjwg you seem to be the benevolent ruler of this project - please let me what you think.

If this goes well, I'd love to contribute more to `nvchecker` over time as I always need such tool in my packaging adventures and your implementation is quite nice 👌

**Comment by lilydjwg** [comment]
A rewrite is ongoing to address several issues e.g. #132. Alongside those changes, I'm planning to use Python's native [namespace packages](https://www.python.org/dev/peps/pep-0420/) for plugins.

Please wait for a few days for a test version of 2.0 to come out. This will be a breaking-changes version and target Python 3.7+.

**Comment by jruzicka-nic** [comment]
Awesome, I'm looking forward to test that hot new stuff ᕕ( ᐛ )ᕗ

**Comment by lilydjwg** [comment]
The new version works now but only a small number of source modules are ported: https://github.com/lilydjwg/nvchecker/tree/nvchecker2/nvchecker_source. Two types of modules are supported, a simpler one for single-function cases and a class-based one for stuff like batch processing (see aur.py).

Documentation hasn't been updated yet.

**Comment by jruzicka-nic** [comment]
I briefly looked at `nvchecker2` - it looks nice, I see you're not afraid to use latest python features :) But there are no docs or examples of howto use custom source yet (it's mentioned as TODO item in `NEW` file 👌) so I'm gonna wait for that before testing further.

Happy Hacking!

**Comment by lilydjwg** [comment]
[The documentation](https://nvchecker.readthedocs.io/en/latest/plugin.html) is done!
