### ISSUE TITLE
Add support to authenticate via a Github App

### ISSUE THREAD

**Issue by KarstenSiemer** [lilydjwg/nvchecker#134]
Hey!
Because of ratelimit and compliance reasons it would be great to be able to authenticate via an Github App.
[Here](https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#authenticating-as-a-github-app) is documented how to do it.
But there is already a project that implemented how to do this.
It is [github3.py](https://github.com/sigmavirus24/github3.py). I'd add a key and environment variable like 'NVCHECKER_GITHUB_APP_ID' & 'NVCHECKER_GITHUB_PRIVATE_KEY_PEM' & 'NVCHECKER_GITHUB_INSTALLATION_ID'.
If these are set, the method [login_as_app_installation](https://github3.readthedocs.io/en/latest/api-reference/github.html#github3.github.GitHub.login_as_app_installation) would be used to get a token.
When we got the token, we'd continue as usual.

What do you think about this? Is there a chance to get this merged if I submit a PR?

**Comment by lilydjwg** [comment]
What's the difference between an GitHub App and a personal access token when used in nvchecker?

There is one problem with github3.py: it's synchronous.

> Is there a chance to get this merged if I submit a PR?

I'm rewriting the whole project (on branch `nvchecker2`) so feature pull requests should be postponed. Also, configuration via environment variables will be replaced by a separate `keyfile`.

**Comment by KarstenSiemer** [comment]
personal access token aren't anonymous - they are attached to a "technical" user.
Here in germany your company can get a confidentiality certification so that you can boast to your customer with your hardened system. Some of these certifications disallow such users and need you do more dynamic authentication with tokens that can expire.
Also Github Apps have dynamic ratelimiting, the bigger your organisation; the higher ratelimit you get.
We are trying to implement Github Apps everywhere possible but are left with a few bot accounts since they only get a ratelimit of 5000, which quite frankly is far from enough for us.

**Comment by lilydjwg** [comment]
I see. Thanks for the explanation.

I'll accept a PR against nvchecker version 2 after the rewrite is done.

**Comment by KarstenSiemer** [comment]
Ok, then I'll close for now. Thanks

**Comment by lilydjwg** [comment]
The version 2 is mostly done and documentation available at https://nvchecker.readthedocs.io/en/latest/.
