### ISSUE TITLE
[v2] Discussions about packaging

### ISSUE THREAD

**Issue by yan12125** [lilydjwg/nvchecker#135]
First, thank you very much for this shining v2! That looks great in many aspects :+1:

Now I'm working on updating PKGBUILD in community/nvchecker for v2. I found an issue and I have a question.

* Not all needed files are installed by setup.py

https://github.com/lilydjwg/nvchecker/blob/376e5ad4991aeabeee77fa8956e0896d0ead0a67/setup.py#L23

This line is missing `nvchecker.lib` and `nvchecker.httpclient`. How about going back to automatic package discovery? For example,
```Diff
diff --git a/setup.py b/setup.py
index d29728b..aa556dc 100755
--- a/setup.py
+++ b/setup.py
@@ -1,6 +1,6 @@
 #!/usr/bin/env python3
 
-from setuptools import setup
+from setuptools import setup, find_namespace_packages
 import nvchecker
 
 # The complex upload command:
@@ -20,7 +20,7 @@ setup(
   platforms = 'any',
   zip_safe = False,
 
-  packages = ['nvchecker', 'nvchecker_source'],
+  packages = find_namespace_packages(exclude=["tests"]),
   install_requires = ['setuptools', 'toml', 'structlog', 'tornado>=6', 'pycurl'],
   extras_require = {
     'vercmp': ['pyalpm'],
```

* Distribute ini2toml?

I believe most nvchecker users will need this after upgrading to v2. How about distributing it via setup.py for first few releases in v2? For example,
```Diff
diff --git a/scripts/ini2toml b/scripts/nvchecker-ini2toml
similarity index 100%
rename from scripts/ini2toml
rename to scripts/nvchecker-ini2toml
diff --git a/setup.py b/setup.py
index d29728b..9123274 100755
--- a/setup.py
+++ b/setup.py
@@ -38,6 +38,7 @@ setup(
       'nvcmp = nvchecker.tools:cmp',
     ],
   },
+  scripts=['scripts/nvchecker-ini2toml'],
   package_data = {'nvchecker_source': ['vcs.sh']},
 
   classifiers = [
```
That will save time for users.

**Comment by lilydjwg** [comment]
Oops I didn't know about `find_namespace_packages` and it doesn't add packages recursively.

However it's still not done yet: #97 hasn't been fully addressed. It's also needed to update the master branch and write the docs for writing plugins.

**Comment by yan12125** [comment]
Looks like the only TODO left is documentation for source plugins?

**Comment by lilydjwg** [comment]
Yes.

**Comment by yan12125** [comment]
Thanks! I will report ASAP whenever I notice something strange.

**Comment by felixonmars** [comment]
@yan12125 Just a heads up: If you plan to update community/nvchecker, don't forget the new bash completion file in scripts/ :apple: )

**Comment by yan12125** [comment]
Could you test this? I don't use bash and I'm lazy 😜
```sh
# Maintainer: Felix Yan <felixonmars@archlinux.org>
# Maintainer: Chih-Hsuan Yen <yan12125@archlinux.org>

pkgname=nvchecker
pkgver=2.0
_commit=0eb586058402095dc0ffde6fab1eca919e1fdf55
pkgrel=1
pkgdesc="New version checker for software releases"
arch=('any')
url="https://github.com/lilydjwg/nvchecker"
license=('MIT')
depends=('python' 'python-setuptools' 'python-toml' 'python-structlog' 'python-appdirs' 'python-tornado' 'python-pycurl')
checkdepends=('python-pytest' 'python-pytest-asyncio' 'python-pytest-httpbin' 'python-flaky')
optdepends=(
  'pyalpm: allow using "sort_version_key = vercmp" in configuration files'
)
source=("$pkgname-$pkgver.tar.gz::https://github.com/lilydjwg/nvchecker/archive/$_commit/$pkgname-$pkgver.tar.gz")
sha512sums=('e5f9f063e0e850907aab2813380a13004cb29eadd6215006c4fa892009bd42ab62b902c3cfb47539fc79337d86e4e8eec787fa54d537aa721ea989f2803b269b')

build() {
  mv nvchecker-$_commit nvchecker-$pkgver

  cd nvchecker-$pkgver
  python setup.py build
}

check() {
  cd nvchecker-$pkgver
  pytest
}

package() {
  cd nvchecker-$pkgver
  # use PYTHONHASHSEED=0 work around https://bugs.python.org/issue34722
  PYTHONHASHSEED=0 python setup.py install --root="$pkgdir" --optimize=1 --skip-build
  install -Dm644 LICENSE -t "$pkgdir"/usr/share/licenses/$pkgname

  # bash completion scripts
  install -Dm644 scripts/nvtake.bash_completion "$pkgdir"/usr/share/bash-completion/completions/nvtake
}

# vim:set ts=2 sw=2 et:
```

**Comment by lilydjwg** [comment]
[Documentation](https://nvchecker.readthedocs.io/en/latest/) is done!

**Comment by lilydjwg** [comment]
I prefer to save disk space unless requested by user. The HTML docs have 4.4MiB in total (with 3.2MiB fonts), and nvchecker is expected to use with Internet access. A separate package doesn't seem worth the effort.

You can inculde the `docs/usage.rst` file though. It's small and quite useful.

**Comment by yan12125** [comment]
Sounds good!

**Comment by yan12125** [comment]
Saw v2 tagged, but I'm away from keyboard for Moon festival 😂 I will update the Arch package on Saturday night.

**Comment by lilydjwg** [comment]
The `sample_config.toml` can be installed to `/usr/share/doc/` too. Also notice that there is a mistake that installs `docs/conf.py`...

**Comment by yan12125** [comment]
nvchecker 2.0-1 pushed to Arch [community]. Thanks for great suggestions on packaging!

https://www.archlinux.org/packages/community/any/nvchecker/
