### ISSUE TITLE
Adding man pages?

### ISSUE THREAD

**Issue by yan12125** [lilydjwg/nvchecker#157]
https://nvchecker.readthedocs.io/en/latest/ is awesome, but some man pages (or maybe another pretty-formatted format not depending on heavy browser stuffs) will be even nicer.

As nvchecker already offers rst documents, rst2man from python-docutils might be an option. The result of `rst2man /usr/share/doc/nvchecker/usage.rst | man -l -` looks good-ish with a few warnings.

pandoc might be another option, but it seems not straightforward. `pandoc -f rst -t man /usr/share/doc/nvchecker/usage.rst -o nvchecker.7` does not generate a readable man page.

P.S. This issue is based on some discussions on the #archlinux-tu IRC channel.

**Comment by lilydjwg** [comment]
This one [nvchecker.1.txt](https://github.com/lilydjwg/nvchecker/files/5323211/nvchecker.1.txt) seems ok?

**Comment by yan12125** [comment]
Wow that looks good! How did you generate it?

**Comment by lilydjwg** [comment]
A custom version of rst2man: https://github.com/lilydjwg/nvchecker/blob/ccae7d8fcfd74f1c81bb3d0e0aa12e6892725738/docs/myrst2man.py

I didn't figure out how to override the `man` target sphinx comes with, though.

**Comment by yan12125** [comment]
> I didn't figure out how to override the man target sphinx comes with, though.

How about just adding the command to `docs/Makefile`?

**Comment by lilydjwg** [comment]
It works now.

**Comment by yan12125** [comment]
Cool! Looking forward to the next version :)
