### ISSUE TITLE
Any plans to bring back desktop notification support?

### ISSUE THREAD

**Issue by guihkx** [lilydjwg/nvchecker#158]
Hi,

After updating to v2.x, I noticed the `-n` flag to show desktop notifications has been removed. It used to be a really useful feature to me, 'cause I made a systemd timer for nvchecker and I'd use the `-n` flag to notify me of any updates. So I was wondering if you intend to bring that option back, or if it's gone for good...

Thanks!

**Comment by lilydjwg** [comment]
It's easy to write a wrapper to do this, e.g. 42dfd483c77d2cc98fd2f155b07aa26357ad5177 (this one uses GObject to call the libnotify library).

It's intended that all kinds of notifications are outside core part of nvchecker like this.

**Comment by guihkx** [comment]
Hey, thanks a bunch for that script! I have no practical knowledge about Python and I didn't want to over-complicate my systemd unit...

Feel free to close this. :)

**Comment by yan12125** [comment]
Hi, how do you think about adding `nvchecker-notify` to setup.py like nvchecker-ini2toml [1]? It is requested downstream [2], and I guess it might be useful for general users.

[1] https://github.com/lilydjwg/nvchecker/blob/v2.1/setup.py#L41
[2] https://bugs.archlinux.org/task/68165

**Comment by lilydjwg** [comment]
Done in f8566f3f91d6e10aaf206bc7308120c4574f37f2. I didn't think there are many people using this (and I'm surprised that it  didn't break since I ported the `notify.py` module to x86_64). :smile:

**Comment by yan12125** [comment]
Cool, thanks!
