### ISSUE TITLE
[Feature Request] Database support

### ISSUE THREAD

**Issue by petronny** [lilydjwg/nvchecker#171]
Saving oldver and newver in the oldver table and newver table in a mysql database:
```ini
[__config__]
oldver = "mysql://username:password@example.com/database?ssl=true"
newver = "mysql://username:password@example.com/database?ssl=true"
```

**Comment by petronny** [comment]
看起来是改 core.read_verfile 和 core.write_verfile 就行

不过可能做一个
```python
def read_ver(uri):
  if uri.startswith('mysql://'):
    return read_ver_mysql(uri)
  if uri.startswith('file://'):
    return read_ver_file(uri)
```
比较好？

**Comment by petronny** [comment]
还有就是我 sqlalchemy 不熟啊。。。

有人有空填坑么。。。没人我再折腾[捂脸]

**Comment by lilydjwg** [comment]
想知道为什么有这样的需求？

**Comment by petronny** [comment]
因为本地 nvchecker 老是因为网络问题报错。。。即使走了代理。。。

然后就想扔 github actions ，所以需要一个好一点的把数据传出来的办法。

**Comment by lilydjwg** [comment]
On Wed, Dec 09, 2020 at 08:05:22AM -0800, Jingbei Li wrote:
> 因为本地 nvchecker 老是因为网络问题报错。。。即使走了代理。。。
> 
> 然后就想扔 github actions ，所以需要一个好一点的把数据传出来的办法。

直接传文件不行么？

-- 
Best regards,
lilydjwg

**Comment by petronny** [comment]
也不是不行。。。

我在github actions最后￼￼￼来个json到数据库的转换也可以。。。

**Comment by petronny** [comment]
啊想起来了，并发nvtake的时候有个文件冲突的问题。

虽然加文件锁也能解决。。。但感觉就是绕。。。

**Comment by lilydjwg** [comment]
On Wed, Dec 09, 2020 at 11:37:49AM -0800, Jingbei Li wrote:
> 啊想起来了，并发nvtake的时候有个文件冲突的问题。
> 
> 虽然加文件锁也能解决。。。但感觉就是绕。。。

为什么你要并发 nvtake 呢？

加个锁吧，flock 一下，很简单的。

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
On Wed, Dec 09, 2020 at 08:44:07AM -0800, Jingbei Li wrote:
> 也不是不行。。。
> 
> 我在github actions最后￼￼￼来个json到数据库的转换也可以。。。

你不能直接把那个 json 上传到某个地方吗？还是说你只有个数据库可用？

-- 
Best regards,
lilydjwg

**Comment by petronny** [comment]
一切都是为了并行打包。。。

文件锁也行。。。也能传文件。。。

就是问题绕一绕总能解决，想找有没有好点的办法。

我先这么试试，要是能搞定我就把这个关了

**Comment by lilydjwg** [comment]
On Wed, Dec 09, 2020 at 09:15:42PM -0800, Jingbei Li wrote:
> 一切都是为了并行打包。。。

并行打包的话，我最近准备实现（等手上的事情、准备写还没写的博客都做完）。

Python 3.9 太棒啦～

-- 
Best regards,
lilydjwg

**Comment by petronny** [comment]
> Python 3.9 太棒啦～

有啥跟并行相关的么？

**Comment by lilydjwg** [comment]
> 有啥跟并行相关的么？

[graphlib.TopologicalSorter](https://docs.python.org/3/library/graphlib.html#graphlib.TopologicalSorter)
