### ISSUE TITLE
Missing support for paging in container registry tag list

### ISSUE THREAD

**Issue by sfudeus** [lilydjwg/nvchecker#189]
I noticed that the tag listing for container registries currently is not capable of processing paginated resources.

Example: 
Using 
```
["prometheus-operator/prometheus-operator"]
source = "container"
container = "prometheus-operator/prometheus-operator"
registry = "quay.io"
```

currently leads to v0.47.0 as latest version, while there are v0.47.1 and v0.48.0 and v0.48.1. 
This seems to be caused by missing support for pagination, which is documented in 
https://docs.docker.com/registry/spec/api/#listing-image-tags. 

Using curl and following the Link-header eventually (in this example with only a 2nd request) leads to the full list of tags.

**Comment by lilydjwg** [comment]
The docs say that endpoint will return _all_ the tags, but in reality no :-(
