### ISSUE TITLE
[Feature Request] Ms repos

### ISSUE THREAD

**Issue by braam** [lilydjwg/nvchecker#191]
Add Microsoft repos

https://packages.microsoft.com/repos/

**Comment by lilydjwg** [comment]
Aren't they just [apt repositories](https://nvchecker.readthedocs.io/en/latest/usage.html#check-apt-repository)?

**Comment by braam** [comment]
I thought so but couldn't get it to work, looks like something is not right but couldn't figure it out in the apt.py code. It does looks correct to my.

My configuration looks like this:

```
["Ms-Teams_Linux"]
source = "apt"
mirror = "https://packages.microsoft.com/repos/ms-teams"
pkg = "ms-teams"
suite = "stable"
repo = "main"
arch = "amd64"
```

Yet I do receive:
`{"logger_name": "nvchecker.core", "name": "Ms-Teams_Linux", "event": "package not found in APT repository", "level": "error"}`

**Comment by lilydjwg** [comment]
Because the package name is just `teams`, not `ms-teams`.

**Comment by braam** [comment]
Hi, whoops indeed you are right.
But now it takes the wrong version, it's displayed 1.2.00.32451 --> should be 1.4.00.13653

It does look like it's not taking the first hit to determine the version in the Packages file.
Do you've any hints to correct this?
