### ISSUE TITLE
crates.io not in documentation

### ISSUE THREAD

**Issue by grawlinson** [lilydjwg/nvchecker#192]
I didn't realise nvchecker had support for crates.io until I searched the source and found [this](https://github.com/lilydjwg/nvchecker/commit/375fb4f14f2fd0b1cb90f377d4a9bfcd7345c8e2) commit.

Is there any reason that it doesn't show up in the documentation on readthedocs?

I'm not entirely sure how the documentation is generated, so apologies if this issue is redundant.

**Comment by lilydjwg** [comment]
I forgot to add documentation for it.
