### ISSUE TITLE
nvcmp is not working ?

### ISSUE THREAD

**Issue by braam** [lilydjwg/nvchecker#202]
I do notice when running the nvcmp with my config file there is a difference in version. But the older version is not updated with the new version. Why is this? when re-running the nvcmp command I'll always have the same difference.... 

```
root@debian:/home/braam# nvcmp -c nvchecker_config.toml   
Fasttel-IP 1.1.2 -> 1.3.2  
root@debian:/home/braam# cat nvchecker_old_ver.json   
{  
  "Fasttel-IP": "1.1.2"  
}
```

**Comment by lilydjwg** [comment]
Because `nvcmp` only compares versions; it doesn't update them. `nvtake` is for updating.

**Comment by braam** [comment]
I'm sorry but I really don't get it...

```
root@debian:/home/braam# cat nvchecker_old_ver.json
{
  "Fasttel-IP": "1.1.2"
}
root@debian:/home/braam# nvcmp -c nvchecker_config.toml 
Fasttel-IP 1.1.2 -> 1.3.2
root@debian:/home/braam# nvtake -c nvchecker_config.toml 
root@debian:/home/braam# cat nvchecker_old_ver.json
{
  "Fasttel-IP": "1.1.2"
}
```

**Comment by braam** [comment]
OK, I get it now... was looking in the wrong direction.
All is working fine now.
