### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by 0xaf1f** [lilydjwg/nvchecker#203]
Hello -- I'm trying to update the Debian package for nvchecker to the latest release, but I'm seeing several tests failing. I was able to get some of them fixed by incorporating the patches https://github.com/lilydjwg/nvchecker/commit/b8afc434300d51e1c77e21f3c3880139e6feb6ce and https://github.com/lilydjwg/nvchecker/commit/44b9f1856fbc68c58ae76840c2e14c3dddd8b22e, but I'm still getting failures in `test_regex` and it looks like some changes to the package (not just the test suite code) were made to address that. Would you mind cutting a new release including these?

many thanks

**Comment by lilydjwg** [comment]
Sure, version 2.5 is released.
