### ISSUE TITLE
Specific name in `vsmarketplace` source raise Error.

### ISSUE THREAD

**Issue by VergeDX** [lilydjwg/nvchecker#216]
I use `nvchecker v2.8`, and the config snippet below will raise an Error:

```````toml
["k--kato.intellij-idea-keybindings"]
source = "vsmarketplace"
vsmarketplace = "k--kato.intellij-idea-keybindings"
```````

```````Python
[E 06-11 21:56:12.003 core:329] k--kato.intellij-idea-keybindings: unexpected error happened error=IndexError('list index out of range')
    Traceback (most recent call last):
      File "/nix/store/q71in8wy9q0nncmf5b8kfvvm258kfzn1-python3.9-nvchecker-2.8/lib/python3.9/site-packages/nvchecker/util.py", line 262, in run_one
        version = await self.func(
      File "/nix/store/q71in8wy9q0nncmf5b8kfvvm258kfzn1-python3.9-nvchecker-2.8/lib/python3.9/site-packages/nvchecker_source/vsmarketplace.py", line 53, in get_version
        version = j['results'][0]['extensions'][0]['versions'][0]['version']
    IndexError: list index out of range
```````

I dig into the source code and found `'filterType: 10'` in query data.  
(https://github.com/lilydjwg/nvchecker/blob/v2.8/nvchecker_source/vsmarketplace.py#L28=)

According to the `enum FilterType`, which can be found in VSCode source code:  
https://github.com/microsoft/vscode/blob/1.68.0/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L179-L188=  
The `filterType: 10` means `SearchText`, and seems used for marketplace searchbox.

In most cases, searching for an extension with "Unique Identifier" can also find itself.  
But in this cases "k--kato.intellij-idea-keybindings", it cannot:

https://marketplace.visualstudio.com/search?term=k--kato.intellij-idea-keybindings&target=VSCode&category=All+categories&sortBy=Relevance

**Comment by lilydjwg** [comment]
As the original author of the code, @Th3Whit3Wolf what do you think?

**Comment by lilydjwg** [comment]
I've made the change as the original author didn't show up.
