### ISSUE TITLE
Newer version of python-gobject breaks nvchecker-notify script

### ISSUE THREAD

**Issue by inglor** [lilydjwg/nvchecker#217]
The newer version of `python-gobject` breaks the notify script:
```
nvchecker-notify -c ~/workspace/pkgbuild-super/nvchecker.toml
Traceback (most recent call last):
  File "/usr/bin/nvchecker-notify", line 14, in <module>
    gi.require_version('Notify', '0.7')
  File "/usr/lib/python3.10/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Notify not available for version 0.7
```

As per @yan12125 suggestion something like this would fix this (already tested it locally)
https://gitlab.gnome.org/GNOME/gnome-tweaks/-/merge_requests/99/diffs

**Comment by lilydjwg** [comment]
Thanks!

**Comment by yan12125** [comment]
Thanks a lot for the fast fix! I cherry-picked it to the Arch Linux package.

**Comment by yan12125** [comment]
Hmm, a libnotify dev is considering reverting the version back to 0.7 (https://gitlab.gnome.org/GNOME/libnotify/-/issues/27#note_1503676)

> Just hardcode `MODULE_VERSION` to `0.7` until the project breaks API.

**Comment by inglor** [comment]
Oh well, the fix in place will work either way ;)
