### ISSUE TITLE
packaging dependency missing

### ISSUE THREAD

**Issue by lazka** [lilydjwg/nvchecker#225]
```
$ nvchecker --version
nvchecker v2.11
$ nvchecker -c config.toml
Error: No module named 'packaging'
```

**Comment by lilydjwg** [comment]
It's an optional dependency. If you use pip, install with `pip install 'nvchecker[pypi]'`.

**Comment by lazka** [comment]
ah, I see, thanks. I was using pipx, so `pipx install "nvchecker[pypi]"` is what I need.

feel free to close
