### ISSUE TITLE
Add direct sort version for cmd

### ISSUE THREAD

**Issue by Christoph-Raab** [lilydjwg/nvchecker#230]
Using cmd could support version sorting as git does.

Nvidia driver from their releases.json contains a number of SemVer releases 

```bash
$ curl -sSf https://docs.nvidia.com/datacenter/tesla/drivers/releases.json | \
  jq -r '.[] | select(.type == "production branch")' | \
  jq -rs '.[].driver_info[].release_version'
525.105.17
525.85.12
525.60.13
515.105.01
[...]
```

Would be nice to not have to use additional tools like sort and tail to get the most resent release, like

```bash
$ curl -sSf https://docs.nvidia.com/datacenter/tesla/drivers/releases.json | \
  jq -r '.[] | select(.type == "production branch")' | \
  jq -rs '.[].driver_info[].release_version' | \
  sort -V | \
  tail -n 1
525.105.17
```

**Comment by lilydjwg** [comment]
You can put the whole command in a `cmd` source.

**Comment by Christoph-Raab** [comment]
Yes, I'm aware of that. This is a feature request that `cmd` supports direct version sorting as `github` does with `use_latest_release` or `use_latest_tag`. Sorry if I didn't make that clear enough.

**Comment by lilydjwg** [comment]
I don't feel a strong reason to do this. `use_latest_release` and `use_latest_tag` don't sort by version. Instead they sort by creation date by GitHub.

**Comment by Christoph-Raab** [comment]
Ok, closing the issue.
