### ISSUE TITLE
`nvcheck -c`'s default value

### ISSUE THREAD

**Issue by Freed-Wu** [lilydjwg/nvchecker#232]
How about:

When `nvchecker.toml` exist in current directory, use it as default configuration.

If not, use `~/.config/nvchecker/nvchecker.toml` as default configuration.

**Comment by lilydjwg** [comment]
No. Path-dependent behavior is bad and very confusing. How many Python learners have once named their learning scripts as `abc.py`, `code.py` or `random.py` etc?

**Comment by Freed-Wu** [comment]
There are many programs using some file in current directory,

such as:

- clangd use `.clangd` as first choice, `~/.config/clangd/config.yaml` as second choice.
- gdb use `.gdbinit` as first choice, `~/.config/gdb/gdbinit` as second choice.
- astyle use `.astylerc` as first choice, `~/.astylerc` as second choice.

Why nvfetcher doesn't use `nvfecther.toml` as first choice, `~/.config/nvfetcher/nvfecther.toml` as second choice?

**Comment by lilydjwg** [comment]
They are related to current project. nvchecker doesn't associate to a project.

**Comment by Freed-Wu** [comment]
I hope I can use `nvchecker` in the following case:

```shell
git clone ssh://aur.archlinux.org/XXX
cd XXX
update.sh
```

Where `update.sh` use `nvfetcher --logger=json`. It is related to current project `XXX`.

**Comment by lilydjwg** [comment]
Probably you want to create an issue for nvfetcher instead.

**Comment by Freed-Wu** [comment]
Sorry, it's a typo. I also use `nvfetcher` but just in NixOS, not ArchLinux.

**Comment by Freed-Wu** [comment]
And nvfetcher uses `nvfetcher.toml` as default config.

**Comment by lilydjwg** [comment]
Still you can implement your logic for finding config file in your `update.sh`.

**Comment by Freed-Wu** [comment]
> nvchecker doesn't associate to a project.

But it actually proves that there is a case that nvchecker associate to a project and it is very useful for AUR users. So why not support it?

**Comment by lilydjwg** [comment]
nvchecker has no intension to work on a per-project basis. It's your wrapper's responsibility to handle that. It would be a breaking change anyway.

**Comment by Freed-Wu** [comment]
OK, I see.
