### ISSUE TITLE
Support netrc file

### ISSUE THREAD

**Issue by blaggacao** [lilydjwg/nvchecker#251]
https://everything.curl.dev/usingcurl/netrc

example (redacted):

```
machine github.com login blaggacao password github_pat_fff...
machine api.github.com login blaggacao password github_pat_fff...
machine gitlab.com password glpat-fff...
```

parsing is available in the python standard lib: https://docs.python.org/3/library/netrc.html

**Comment by lilydjwg** [comment]
I can accept a patch implementing this.
