### ISSUE TITLE
`taskName=Task-2` gets appended to the output of `nvchecker`

### ISSUE THREAD

**Issue by guihkx** [lilydjwg/nvchecker#267]
E.g.:

```
$ nvchecker -c sources.toml
[I 04-23 18:09:50.355 core:408] myApp: updated from 1.0.0 to 1.0.1 taskName=Task-2
```

I believe this is somehow related to [Python 3.12](https://docs.python.org/3/library/logging.html#:~:text=Changed%20in%20version%203.12%3A%20taskName%20was%20added.):

>*Changed in version 3.12:* `taskName` was added.

**Comment by lilydjwg** [comment]
Thanks! This should have been fixed (but I didn't test because Python 3.12 is still not available for Arch).
