### ISSUE TITLE
Support codeberg as source

### ISSUE THREAD

**Issue by txtsd** [lilydjwg/nvchecker#271]
Please add support to check tags on codeberg.org

**Comment by lilydjwg** [comment]
Does [the "git" source](https://nvchecker.readthedocs.io/en/latest/usage.html#check-git-repository) work for you?

**Comment by txtsd** [comment]
In the interim it does, but I'll try and open a PR for this myself soon.

**Comment by fossdd** [comment]
This is mostly covered by the gitea source (with host=codeberg.org). I was thinking of creating a forgejo/codeberg source, but thats mostly a copy of gitea...

**Comment by txtsd** [comment]
gitea with host=codeberg.org works for me
