### ISSUE TITLE
GitHub: option to use release name instead of tag

### ISSUE THREAD

**Issue by flying-sheep** [lilydjwg/nvchecker#278]
[Mamba’s releases](https://github.com/mamba-org/mamba/releases) have `tag_name`s like “2024.09.30” and `name`s like “2.0.1”:

```console
$ gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/mamba-org/mamba/releases/latest | jq
{
  "id": 177705346,
  "tag_name": "2024.09.30",
  "target_commitish": "main",
  "name": "2.0.1",
  "draft": false,
  "prerelease": false,
  "tarball_url": "https://api.github.com/repos/mamba-org/mamba/tarball/2024.09.30",
  "zipball_url": "https://api.github.com/repos/mamba-org/mamba/zipball/2024.09.30",
  ...
}
```

It would be great to have an option to use the actual name, not the tag name.

**Comment by flying-sheep** [comment]
Thanks, this is great! You write:

> For historical reasons it doesn't return the release name. See below to change

And I think that it makes sense that both are possible. Most projects use the tag and not the name!

**Comment by lilydjwg** [comment]
It is inconsistent with "include_prereleases", but unfortunately it's too late to change. Maybe I'd add support to specify this to `false` to the counterpart.

**Comment by lilydjwg** [comment]
> Maybe I'd add support to specify this to `false` to the counterpart.

I added this too.

**Comment by flying-sheep** [comment]
Works wonderfully, thank you!
