### ISSUE TITLE
Group in documentation Gogs, Gitea, Forgejo, Codeberg

### ISSUE THREAD

**Issue by Popolon** [lilydjwg/nvchecker#287]
Gitea is a fork of Gogs, Forgejo is a fork of Gitea. Codeberg used Gitea before they forked Forgejo, and now use this last one.

It could be useful to write in the documentation chapter about Gitea, that both forges use the same API or that these ones are compatible, so people don't have to open a search at tickets or open a new one.

**Comment by lilydjwg** [comment]
Thanks, I've added a section for them. I didn't know their somewhat complex relations.
