### ISSUE TITLE
version comparison gives bad results

### ISSUE THREAD

**Issue by lilydjwg** [lilydjwg/nvchecker#45]
Maybe we should remove the logic and use equation to judge if it's updated? cc @felixonmars @farseerfc 

See also https://github.com/archlinuxcn/repo/issues/351 and #40.

This logic was implemented three years ago by a5aad83a51cc1d145efcd41faab81654ae35cee0.

**Comment by lilydjwg** [comment]
There are a lot of changes missed:
```
android-ndk r13-1 -> r13b-1
cargo-nightly 2016-11-28 -> 0.18.0-nightly (ad92930 2017-02-03)
evdi 1.3.43-1 -> 1.2.64-1
kmozillahelper 0.6.5-1 -> 1:0.6.4-1
libui-git r1914.84b392d-1 -> alpha3.1.r281.g5fa7ba4-1
ncurses5-compat-libs 6.0-4 -> 6.0+20161224-1
pdftk-bin 2.02_4-1 -> 2.02_4_b1-2
rust-nightly 2017-02-03 -> 2017-02-04
```

**Comment by felixonmars** [comment]
+1, actual use of version comparison was implemented in use_max_tag support too, and I think that's where it belongs.

**Comment by farseerfc** [comment]
Agree to use equal for pkgver.
But for pkgrel I don't know whether this change will affect bumping pkgrel only in archlinuxcn. Will it replace the bumped pkgrel with AUR pkgrel ?

**Comment by lilydjwg** [comment]
On Sun, Feb 05, 2017 at 08:35:51PM -0800, Jiachen Yang wrote:
> Agree to use equal for pkgver.
> But for pkgrel I don't know whether this change will affect bumping pkgrel only in archlinuxcn. Will it replace the bumped pkgrel with AUR pkgrel ?

It won't affect AUR since nvchecker only tells lilac which packages are
updated. AUR-sourced packages don't use the detected version info.

-- 
Best regards,
lilydjwg

**Comment by farseerfc** [comment]
Great. Let's change that
