### ISSUE TITLE
Feature Request: Support Docker Hub images

### ISSUE THREAD

**Issue by vladgh** [lilydjwg/nvchecker#59]
It would be really nice if this would also support Docker images (particularly https://hub.docker.com). Their API documentation is  https://docs.docker.com/registry/spec/api.

Example for tags: https://registry.hub.docker.com/repositories/library/alpine/tags/

Thank you in advance.

**Comment by lilydjwg** [comment]
I won't have the time to implement this, but pull requests are welcome.
