### ISSUE TITLE
ignored_tags not powerful enough to filter github releases not available with the releases API

### ISSUE THREAD

**Issue by eli-schwartz** [lilydjwg/nvchecker#70]
See for example https://github.com/EFForg/https-everywhere/

No Github releases exist, so I need use_max_tag, but they've also got lots of legacy tags, so I'd need to use this too, but unfortunately that is 1) insane, 2) "IndexError: list index out of range":

`ignored_tags = trac-5275-1 testtag deterministic-0.1 chrome-0.0.8.1 chrome-0.0.8.1 chrome-0.0.8.4 chrome-0.0.8.4 chrome-0.0.8.5 chrome-0.0.8.5 chrome-0.0.8.6 chrome-0.0.8.6 chrome-0.0.8.7 chrome-0.0.8.7 chrome-0.0.8.8 chrome-0.0.8.8 chrome-2012.1.26 chrome-2012.10.18 chrome-2012.10.18 chrome-2012.10.31 chrome-2012.10.31 chrome-2012.10.9 chrome-2012.10.9 chrome-2012.12.17 chrome-2012.12.17 chrome-2012.2.27 chrome-2012.2.27 chrome-2012.2.6 chrome-2012.2.6 chrome-2012.2.6.1 chrome-2012.2.6.1 chrome-2012.2.9 chrome-2012.2.9 chrome-2012.3.14 chrome-2012.3.14 chrome-2012.3.9 chrome-2012.3.9 chrome-2012.5.1 chrome-2012.5.1 chrome-2012.6.18 chrome-2012.6.18 chrome-2012.6.21 chrome-2012.6.21 chrome-2012.8.15 chrome-2012.8.15 chrome-2012.8.16 chrome-2012.8.16 chrome-2012.9.10 chrome-2012.9.10 chrome-2012.9.21 chrome-2012.9.21 chrome-2013.1.18 chrome-2013.1.18 chrome-2013.10.16 chrome-2013.10.16 chrome-2013.3.7 chrome-2013.3.7 chrome-2013.4.30 chrome-2013.4.30 chrome-2013.6.4 chrome-2013.6.4 chrome-2013.7.10 chrome-2013.7.10 chrome-2013.8.16 chrome-2013.8.16 chrome-2013.8.17 chrome-2013.8.17 chrome-2014.1.3 chrome-2014.1.3 chrome-2014.11.25 chrome-2014.11.25 chrome-2014.4.14 chrome-2014.4.14 chrome-2014.4.14.1 chrome-2014.4.14.1 chrome-2014.4.15 chrome-2014.4.15 chrome-2014.4.16 chrome-2014.4.16 chrome-2014.4.25 chrome-2014.4.25 chrome-2014.6.25 chrome-2014.6.25 chrome-2014.6.26 chrome-2014.6.26 chrome-2014.8.22 chrome-2014.8.22 chrome-2015.1.22 chrome-2015.1.22 chrome-2015.12.16 chrome-2015.12.16 chrome-2015.3.23 chrome-2015.3.23 chrome-2015.3.31 chrome-2015.3.31 chrome-2015.4.23 chrome-2015.4.23 chrome-2015.4.7 chrome-2015.4.7 chrome-2015.5.12 chrome-2015.5.12 chrome-2015.5.28 chrome-2015.5.28 chrome-2015.7.13 chrome-2015.7.13 chrome-2015.7.17 chrome-2015.7.17 chrome-2015.8.13 chrome-2015.8.13 chrome-2016.10.20 chrome-2016.10.20 chrome-2016.11.30 chrome-2016.11.30 chrome-2016.11.8 chrome-2016.11.8 chrome-2016.12.19 chrome-2016.12.19 chrome-2016.2.18 chrome-2016.2.18 chrome-2016.2.23 chrome-2016.2.23 chrome-2016.3.23 chrome-2016.3.23 chrome-2016.4.4 chrome-2016.4.4 chrome-2016.5.10 chrome-2016.5.10 chrome-2016.6.9 chrome-2016.6.9 chrome-2016.7.18 chrome-2016.7.18 chrome-2016.7.19 chrome-2016.7.19 chrome-2016.8.24 chrome-2016.8.24 chrome-2016.9.1 chrome-2016.9.1 chrome-2016.9.21 chrome-2016.9.21 chrome-2017.1.25 chrome-2017.1.25 chrome-2017.2.13 chrome-2017.2.13 chrome-2017.3.17 chrome-2017.3.17 chrome-2017.3.9 chrome-2017.3.9 chrome-2017.4.19 chrome-2017.4.19 chrome-2017.4.5 chrome-2017.4.5 chrome-2017.5.22 chrome-2017.5.22 chrome-2017.5.8 chrome-2017.5.8 chrome-2017.6.20 chrome-2017.6.20 chrome-2017.6.5 chrome-2017.6.5 chrome-2017.7.18 chrome-2017.7.18 chrome-2017.7.5 chrome-2017.7.5`

Needless to say, being able eliminate the 79 tags beginning with "chrome-" from being considered would be very useful here.

**Comment by lilydjwg** [comment]
It seems to be great to have `exclude_tags_pattern` and `include_tags_pattern` options.

**Comment by lilydjwg** [comment]
I've only added a `include_tags_pattern` as it seems to be sufficient.

**Comment by eli-schwartz** [comment]
Since re.search supports PCRE lookahead/lookbehind matches, anyone who just wants to exclude a given pattern can do that too with a bit of effort. But mostly people will expect a certain pattern to include, so you're right that this is probably sufficient.

Thanks!
