### ISSUE TITLE
`RuntimeWarning` with the aiohttp backend

### ISSUE THREAD

**Issue by yan12125** [lilydjwg/nvchecker#74]
For example, in this Travis CI test: https://travis-ci.org/lilydjwg/nvchecker/jobs/395356024
```
==================== 50 passed, 6 skipped in 15.02 seconds =====================
sys:1: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
The command "pytest" exited with 0.
```

Running the nvchecker command results in the same warning
```
$ nvchecker
sys:1: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
[E 06-26 22:38:31.527 base_events:1266] Unclosed client session
    client_session: <nvchecker.source.aiohttp_httpclient.BetterClientSession object at 0x10a637e10>
```

BTW, why are there multiple HTTP backends? It's confusing and bring issues to packaging. For example, Arch Linux's pacman does not support the OR operator (`|`) like dpkg of Debian, so aiohttp, tornado and pycurl are listed as optional dependencies. User intervention are required to make nvchecker actually works. If the plan is to replace Tornado+PyCURL with aiohttp as described in #53, I vote for dropping old backends, so that packagers can just list aiohttp as a normal dependency.

**Comment by felixonmars** [comment]
There was an attempt to port to aiohttp completely, but turns out the aiohttp backend has some issues with my massive number of items. I never found a way to make it complete successfully so I still stick with the tornado backend for now, with the hope that someone (maybe myself) found a way to fix it before completely dropping the old backend.

**Comment by lilydjwg** [comment]
The aiohttp has some issues, what you've described here is one of those. And aiohttp doesn't support HTTP/2.

Tornado + pycurl works great but it requires a C extension to work.

Tornado alone works but no HTTP/2 support, no proxy support, no Keep-Alive suport.

So Tornado + pycurl is preferred if you can use it, otherwise try aiohttp.

**Comment by yan12125** [comment]
Does the combination Tornado+PyCURL have other issues? Depending on native codes sounds minor as pycurl is already packaged on most systems.

**Comment by eli-schwartz** [comment]
> Arch Linux's pacman does not support the OR operator (|) like dpkg of Debian, so aiohttp, tornado and pycurl are listed as optional dependencies

They don't look very optional to me, aiohttp is simply ignored completely.

More interestingly, the **setuptools** metadata completely ignores all three.

**Comment by yan12125** [comment]
> They don't look very optional to me, aiohttp is simply ignored completely.

I guess you were about the nvchecker package in [community]? [aur/nvchecker-git](https://aur.archlinux.org/packages/nvchecker-git) is more accurate IMO.

> More interestingly, the setuptools metadata completely ignores all three.

AFAIK setuptools does not provide an OR operator, either. A possible way might be declaring optional dependencies in `extras`.

**Comment by eli-schwartz** [comment]
Uh...

Yes, I naturally gravitated to the version in community. ;)

Honestly from the sound of it I would consider tornado+pycurl mandatory, and not recommend aiohttp at all.

That being said, setup.py does not list extras_require for pyalpm either, which I guess it should. Unsure if the PKGBUILD should list optdepends on git/hg, when it doesn't do the same for bzr or svn.

**Comment by lilydjwg** [comment]
> More interestingly, the setuptools metadata completely ignores all three.

That's because I don't know what to do with alternative dependencies.

I'm going to do the following changes wrt packaging:

* use `extras_requires` in setup.py
* make tornado+pycurl required for nvchecker-git

**Comment by lilydjwg** [comment]
#86 has fixed the aiohttp warnings.
