### ISSUE TITLE
Unable to run nvchecker executable

### ISSUE THREAD

**Issue by ltfschoen** [lilydjwg/nvchecker#78]
I'm having difficulty trying to install the executable by following these steps on macOS 10.13.4 using `python --version` Python 3.6.2. Note that I haven't used Python for a while.

* Clone the repo
```
git clone https://github.com/lilydjwg/nvchecker;
cd nvchecker;

* Build and install the package
```
python setup.py install
```
The above creates a build/ directory (containing bdist.macosx-10.12-x86_64 and folder lib) and dist/ directory (containing nvchecker-1.2.dev0-py3.6.egg)

* Run the package (Attempt 1)
```
./nvchecker --help
-bash: ./nvchecker: is a directory
```

* Run the package (Attempt 2)
```
$ python ./build/lib/nvchecker/main.py
Traceback (most recent call last):
  File "./build/lib/nvchecker/main.py", line 10, in <module>
    from .lib import notify
ModuleNotFoundError: No module named '__main__.lib'; '__main__' is not a package
```

**Comment by lilydjwg** [comment]
You can't run like that.

After `python setup.py install`, try `nvchecker --help`. It should work. The build directory is termporary.

**Comment by lilydjwg** [comment]
I've updated the outdated README.
