### ISSUE TITLE
How to setup NVCHECKER_GITHUB_TOKEN?

### ISSUE THREAD

**Issue by FreelancePentester** [lilydjwg/nvchecker#79]
Hi,
I tried to setup NVCHECKER_GITHUB_TOKEN variable, but it doesn't work.
[__config__]
oldver = old_ver.txt
newver = new_ver.txt
NVCHECKER_GITHUB_TOKEN = my_token

Please help me.
Thanks!

**Comment by felixonmars** [comment]
It's an environment variable, not a config option (yet?).

**Comment by lilydjwg** [comment]
It's an environment variable. Use like this:

```sh
NVCHECKER_GITHUB_TOKEN=your_token nvchecker config.ini
```

You can also provide it in a `keyfile` like this (You should give this file a stricter permission like 600):

```ini
[keys]
github = your_token
```

And refer to this file in your config:
```ini
[__config__]
keyfile = /path/to/keyfile
```

This file is seperate so you can better protect your secrets while sharing other parts to others (or just store them publicly in the cloud).

**Comment by FreelancePentester** [comment]
Thank you so much!
