### ISSUE TITLE
support include_tags_pattern for gitlab

### ISSUE THREAD

**Issue by juliantaylor** [lilydjwg/nvchecker#83]
hi
gitlab does not have a include_tags_pattern configuration like github does. The configuration is useful to ignore e.g alpha/beta/rc versions.
Can this configuration also be added to gitlab (and probably all other git based check backends)?

**Comment by lilydjwg** [comment]
We can instead support include/exclude patterns on all sources that may get a list of results.

I'll take a look some time later.

**Comment by dvzrv** [comment]
This would be very helpful, indeed!
