### ISSUE TITLE
pull in configuration from $XDG_CONFIG_HOME automatically

### ISSUE THREAD

**Issue by dvzrv** [lilydjwg/nvchecker#96]
(On Linux at least) It would be pretty awesome, if a call to `nvchecker` leads to an automatic resolve of the application using a configuration below `~/.config/nvchecker/nvchecker.ini` (i.e. `$XDG_CONFIG_HOME/nvchecker/nvchecker.ini`), if available.
This is [standard behavior](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and a good default.

If you include [appdirs](https://pypi.org/project/appdirs/), you can easily make this cross-platform.

**Comment by lilydjwg** [comment]
Unfortunately omitting the configuration file in arguments won't work well for `nvtake` and `nvcmp`.

Why do you think it's better to use a default file? It shouldn't be very inconvenient to specify a path and you can always create an alias for your usual repeating command.

**Comment by dvzrv** [comment]
On 2019-02-24 22:13:01 (-0800), 依云 wrote:
> Unfortunately omitting the configuration file in arguments won't work
> well for `nvtake` and `nvcmp`.
Those two can just as well use the same default. I don't see a problem
with that. If one wants to specify another configuration, this is still
possible.

> Why do you think it's better to use a default file? It shouldn't be
> very inconvenient to specify a path and you can always create an alias
> for your usual repeating command.

Well, it *is* inconvenient to specify a file! One has to type *n* more
characters. :)
It is even more inconvenient to create an alias for it, if good practice
is to use a common default path for a configuration. This rather feels
like working around an insufficiency.

However, it is very convenient to rely on an established standard and do
things the same way as one can expect them from other tools requiring a
configuration file (have a canonical default location in a standardized
path).

From the top of my head I could give 30 different examples, that (more
or less) cleanly use this standard (and those are not only python
programs). Looking into `~/.config/`, I find plenty more!

I guess the question here is: How many configurations for nvchecker does
the average user actually have or need?
Are there use-cases where one would want to have plenty?
I have around 270 something packages and for me having all of the ones I
check in one configuration is no problem, but maybe it is for users with
many more packages in one configuration?
Also: Which of the users would be considered an edge-case? The one with
only one configuration, or the one with plenty?

**Comment by lilydjwg** [comment]
On Mon, Feb 25, 2019 at 01:48:38AM -0800, David Runge wrote:
> On 2019-02-24 22:13:01 (-0800), 依云 wrote:
> > Unfortunately omitting the configuration file in arguments won't work
> > well for `nvtake` and `nvcmp`.
> Those two can just as well use the same default. I don't see a problem
> with that. If one wants to specify another configuration, this is still
> possible.

You can't give a second argument when you omit the first one.

> > Why do you think it's better to use a default file? It shouldn't be
> > very inconvenient to specify a path and you can always create an alias
> > for your usual repeating command.
> 
> Well, it *is* inconvenient to specify a file! One has to type *n* more
> characters. :)
> It is even more inconvenient to create an alias for it, if good practice
> is to use a common default path for a configuration. This rather feels
> like working around an insufficiency.

You can rely on your command history or crontab or whatever you can use.
Yes these are work-arounds but I don't want to break compatibility.

For example, when one invokes `nvtake python ruby perl`, should the
program uses the default config or the file named `python`? Different
behaviours regarding to random existing files sound no good.

If no solution for this is found, I will put off this to version 2.0
that I'm not sure when it will come.

-- 
Best regards,
lilydjwg

**Comment by dvzrv** [comment]
> You can't give a second argument when you omit the first one.

Hm, I guess in that case the configuration file should not be an
argument at all, but always be provided by a flag (e.g. `-c`) and
arguments should be solely reserved for names of packages, whereas
nvchecker itself wouldn't even need to accept arguments to itself
anymore.

> You can rely on your command history or crontab or whatever you can
> use.

Sure.

> Yes these are work-arounds but I don't want to break compatibility.

Compatibility to what? You do have versioning for this tool! Move fast,
break things!

> For example, when one invokes `nvtake python ruby perl`, should the
> program uses the default config or the file named `python`? Different
> behaviours regarding to random existing files sound no good.

The default configuration. Also, as mentioned above: Providing the
configuration file should probably be done through a flag in all cases.
That would be much more failsafe.

> If no solution for this is found, I will put off this to version 2.0
> that I'm not sure when it will come.

-- 
https://sleepmap.de

**Comment by lilydjwg** [comment]
On Mon, Feb 25, 2019 at 02:09:58PM +0000, David Runge wrote:
> [...]
> 
> Compatibility to what? You do have versioning for this tool! Move fast,
> break things!

No.

I'm sticking to Awesome 3.5.9. I don't use neovim. I hesitate to use any
less popular Go programs. Because it takes too much effort to fix broken
things continously (and it takes time to notice broken automated scripts).

I'm using semver, meaning that break changes will appear in 2.x, not in
1.x. I'd like to give it some time to accumulate some more breaking
changes so that I don't need every user to actively update things from
time to time.

-- 
Best regards,
lilydjwg

**Comment by lilydjwg** [comment]
Closing for #97.
